server {
    listen 80;
    server_name _;
    
    # Activar compresión GZIP
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml application/json application/javascript application/xml+rss application/atom+xml image/svg+xml;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Single Page Application Support
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache Control para Assets (CSS/JS/Imagenes/Fuentes)
    location ~* \.(?:css|js|woff2?|eot|ttf|otf|svg|png|jpe?g|gif|ico)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
