exclude = ["scripts"]

[lint]
ignore = [
    "E711", # Comparison to None (SQLAlchemy needs == None / != None)
    "E712", # Comparison to True/False (SQLAlchemy needs == True / == False)
    "E402", # Module level import not at top of file
    "F841"  # Local variable assigned to but never used
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
